version: '3.8'

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ${CONFIG_BASE_PATH}/jellyseerr:/app/config
    extra_hosts:
      - "radarr.docker.internal:127.0.0.1"
      - "sonarr.docker.internal:127.0.0.1"
      - "bazarr.docker.internal:127.0.0.1"
      - "prowlarr.docker.internal:127.0.0.1"
      - "lidarr.docker.internal:127.0.0.1"
      - "overseerr.docker.internal:127.0.0.1"
      - "jellyfin.docker.internal:127.0.0.1"
      - "jellyseerr.docker.internal:127.0.0.1"
    restart: unless-stopped
    networks:
      - mediacheky_mediacheky-net

networks:
  mediacheky_mediacheky-net:
    external: true
