version: '3.8'

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${CONFIG_BASE_PATH}/jellyfin:/config
  - ${MEDIACHEKY_MEDIA_PATH}:/MEDIACHEKY_LIBRARY
    restart: unless-stopped
    networks:
      - mediacheky_mediacheky-net

networks:
  mediacheky_mediacheky-net:
    external: true
