version: '3.8'

services:
  jellyfin:
    image: {{ .Image }}
    container_name: {{ .ContainerName }}
    labels:
      - "mediacheky.managed=true"
    environment:
      - PUID={{ .Global.PUID }}
      - PGID={{ .Global.PGID }}
      - TZ={{ .Global.Timezone }}
    volumes:
      - {{ .Paths.Config }}:/config
      - {{ .Global.MediaPath }}:/MEDIACHEKY_LIBRARY
    {{- if and .HostPort (gt .HostPort 0) }}
    ports:
      - "{{ .HostPort }}:8096"
    {{- end }}
    extra_hosts:
      - "jellyfin.docker.internal:127.0.0.1"
      - "radarr.docker.internal:127.0.0.1"
      - "sonarr.docker.internal:127.0.0.1"
    networks:
      - {{ .Network }}
    restart: {{ .RestartPolicy }}

networks:
  {{ .Network }}:
    external: true
