version: '3.8'

services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${CONFIG_BASE_PATH}/services-volumes/prowlarr:/config
    restart: unless-stopped
    networks:
      - mediacheky_mediacheky-net

networks:
  mediacheky_mediacheky-net:
    external: true
