services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ${CONFIG_BASE_PATH}/services-volumes/radarr:/config
      - ${MEDIACHEKY_MEDIA_PATH}:/MEDIACHEKY_LIBRARY
    networks:
      - {{ .Network }}
    restart: unless-stopped
    # NO ports section = internal network only

networks:
  {{ .Network }}:
    external: true
