version: '3.8'
services:
  radarr:
    image: {{ .Image }}
    container_name: {{ .ContainerName }}
    environment:
      - PUID={{ .Global.PUID }}
      - PGID={{ .Global.PGID }}
      - TZ={{ .Global.Timezone }}
      {{- if .Umask }}
      - UMASK={{ .Umask }}
      {{- end }}
    volumes:
      - {{ .Paths.Config }}:/config
  - {{ .Global.MediaPath }}:/MEDIACHEKY_LIBRARY
    {{- if .ExposePort }}
    ports:
      - "{{ if .HostPort }}{{ .HostPort }}{{ else }}{{ .Port }}{{ end }}:7878"
    {{- end }}
    networks:
      - mediacheky-net
    restart: {{ .RestartPolicy }}

networks:
  mediacheky-net:
    external: true
