version: '3.8'
services:
  radarr:
    image: {{ .Image }}
    container_name: {{ .ContainerName }}
    environment:
      - PUID={{ .Global.PUID }}
      - PGID={{ .Global.PGID }}
      - TZ={{ .Global.Timezone }}
      {{- if .Umask }}
      - UMASK={{ .Umask }}
      {{- end }}
    volumes:
      - {{ .Paths.Config }}:/config
      - {{ .Global.MediaPath }}:/MEDIACHEKY_LIBRARY
    {{- if and .HostPort (gt .HostPort 0) }}
    ports:
      - "{{ .HostPort }}:7878"
    {{- end }}
    extra_hosts:
      - "radarr.docker.internal:127.0.0.1"
      - "sonarr.docker.internal:127.0.0.1"
      - "bazarr.docker.internal:127.0.0.1"
      - "prowlarr.docker.internal:127.0.0.1"
      - "lidarr.docker.internal:127.0.0.1"
      - "overseerr.docker.internal:127.0.0.1"
      - "jellyfin.docker.internal:127.0.0.1"
      - "jellyseerr.docker.internal:127.0.0.1"
    networks:
      - mediacheky-net
    restart: {{ .RestartPolicy }}

networks:
  mediacheky-net:
    external: true
