#!/bin/bash
# Script to setup .env with correct PUID/PGID for current user

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

echo "🔧 MediaCheky - User Permissions Setup"
echo ""

# Get current user's UID and GID
PUID=$(id -u)
PGID=$(id -g)

echo "📋 Detected user permissions:"
echo "   PUID (User ID):  $PUID"
echo "   PGID (Group ID): $PGID"
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env file already exists at: $ENV_FILE"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled. Existing .env file preserved."
        exit 0
    fi
fi

# Create .env file
cat > "$ENV_FILE" << EOF
# MediaCheky Environment Configuration
# Auto-generated by setup-permissions.sh

# ============================================================================
# User/Group Configuration
# ============================================================================
# These values match your host user to avoid permission issues
PUID=$PUID
PGID=$PGID

# ============================================================================
# Core Configuration
# ============================================================================
MEDIACHEKY_SERVER_PORT=80
MEDIACHEKY_SERVER_PORT_SSL=443
MEDIACHEKY_MEDIA_PATH=./volumes/library

# ============================================================================
# Data Paths
# ============================================================================
MEDIACHEKY_APP_DATA=./volumes/mediacheky-data

# ============================================================================
# Debug & Development (uncomment to enable)
# ============================================================================
# MEDIACHEKY_APP_ENVIRONMENT=development
# MEDIACHEKY_APP_LOG_LEVEL=debug
EOF

echo "✅ .env file created successfully!"
echo ""
echo "📁 Location: $ENV_FILE"
echo ""
echo "🚀 Next steps:"
echo "   1. Review the .env file if needed"
echo "   2. Start MediaCheky with: make dev"
echo ""
